programs:

    empty:
      cmd: ls

    fail:
      cmd: "/bin"
      umask: 077
      workingdir: "/tmp"
      autostart: true
      startretries: 3
      stderr: "/tmp/taskFAIL.stderr"

    cat:
      cmd: "/bin/cat"
      numprocs: 3
      umask: 644
      workingdir: "/tmp"
      autostart: false
      autorestart: "unexpected"
      exitcodes:
        - 0
        - 2
      #  - 15
      #  - 9
      startretries: 4
      starttime: 4
      stopsignal: "TERM"
      stoptime: 5
      stdout: "/tmp/taskcat.stdout"
      stderr: "/tmp/taskcat.stderr"
      env:
          HOME: "/HOME"

    ls:
      cmd: "ls -R /"
      numprocs: 3
      umask: 077
      workingdir: "/tmp"
      autostart: true
      autorestart: true
      exitcodes:
        - 0
        - 2
      startretries: 3
      starttime: 1
      stopsignal: "TERM"
      stoptime: 10
      stdout: "/tmp/taskls.stdout"
      stderr: "/tmp/taskls.stderr"

    wc:
      cmd: "/usr/bin/wc"
      numprocs: 0
      umask: 077
      autorestart: "djkdd"
      exitcodes:
        - 0
        - 15
      startretries: 3
      stopsignal: "TERM"
      starttime: 1
      stoptime: 10
      stdout: "/tmp/taskwc.stdout"
